### ISSUE TITLE
Improve authentication process

### ISSUE THREAD

**Issue by amenat** [world-class/compass#38]
Some suggestions received:

~~- [ ] Password double-typing to improve accessibility.~~
~~- [ ] Fix duplicate alerts for account/profile verification.~~
~~- [ ] Show proper errors in login/registration forms~~
~~- [ ] Account creation form: Change the label of the button from "Submit" to "Create account"~~
~~- [ ] Use red alerts only if an error occurred, use amber or blue otherwise~~
~~- [ ] "Already an account?" -> "Already have an account?"~~ 
- [ ] Allow logins with slack. Since we are already using it for account verification it would be a good idea to let users log in directly with Slack.

**Comment by arjunmuralidharan** [comment]
- Account creation form: Change the label of the button from "Submit" to "Create account"
- Use red alerts only if an error occurred, use amber or blue otherwise
- "Already an account?" -> "Already have an account?"

**Comment by arjunmuralidharan** [comment]
https://getbootstrap.com/docs/4.0/components/forms/#validation

**Comment by amenat** [comment]
Just documenting some private discussions.

We will remove local authentication and solely rely on Slack for authentication. I'll be submitting a PR for this soon.
