### ISSUE TITLE
JS error on account creation

### ISSUE THREAD

**Issue by Arundel2017** [world-class/compass#44]
On creating an account I encountered the error message attached.

Steps taken:

Followed the login -> register for an account steps from the home page
Entered name, email, and password, hit 'submit' or equivalent button.
Was taken to the route: http://www.ucompass.tech/profile where I saw this error message.

![registrationError](https://user-images.githubusercontent.com/29566187/96338760-1e025c80-1088-11eb-9cbc-45407d359b52.png)

**Comment by arjunmuralidharan** [comment]
It looks like we are not handling the case where a student has written no reviews yet, and hence `reviews` is undefined. I think I can fix this.

**Comment by Arundel2017** [comment]
Yep, I'm met with the same error when I try to add my first review, it takes me to the same 'profile' route where I get the same JS error.

**Comment by amenat** [comment]
This was apparently due to some configuration error (while deploying to production server). I cannot reproduce this locally and now on prod setup too.

I am leaving this issue and #45 open for further exploration and making things more robust.

**Comment by arjunmuralidharan** [comment]
I've added some basic checking to catch this error in the future.
