### ISSUE TITLE
Cannot retrieve any full review

### ISSUE THREAD

**Issue by Arundel2017** [world-class/compass#45]
Steps taken:

Following any link to any specific review - for example following the path reviews -> link to specific review from the home page, I get the following error: 
![reviewNotFound](https://user-images.githubusercontent.com/29566187/96338947-49397b80-1089-11eb-96d9-16b41d372a59.png)

It seems the end of the url with the review id is not being appended properly or similar error?

**Comment by amenat** [comment]
This has been resolved with #58 and fixing some config on server.
