### ISSUE TITLE
Reduce size of headings in generated HTML of markdown reviews

### ISSUE THREAD

**Issue by amenat** [world-class/compass#73]
Just an opinion. This looks bit too huge compared to rest of the text.

![image](https://user-images.githubusercontent.com/9079960/97113032-b0040800-170d-11eb-86c0-c649aae1308f.png)

**Comment by guyus15** [comment]
Hi, I'd like to do this issue

**Comment by BlairCurrey** [comment]
@guyus15 thanks for taking an interesting in helping. Feel free to assign yourself to this issue and reach out if you need any help getting started.

Please take a look at the ["How to Contribute" section](https://github.com/world-class/compass#how-to-contribute) of the readme for instructions on how to get started. The readme also includes instructions for how to set up the development environment. Feel free to offer feedback on these instructions if you find anything lacking.

Just something to note about this issue... we don't currently have a CSS stylesheet. One will need to be created in the `public` folder.
