### ISSUE TITLE
After a 500: internal server error, going back loses the module and session and unable to select original without selecting another first

### ISSUE THREAD

**Issue by ruthsykes** [world-class/compass#82]
Journey:
1. Complete a review for ITP1, October to March 2020, valid content for Difficulty, Workload, Rating; Comment field contains an emoji (invalid character)
2. Submit
3. 500: internal server error
4. Browser back button
5. All fields except Module and Session are remembered
6. Original Module and Session (ITP1, October to March 2020) are unable to be selected - visible in list but clicking does not select them
7. Select any other Module and Session
8. Able now to select original Module and Session
9. Remove cat emoji from comment field :( 
10. Submit (successfully)

I will upload a screen recording on Slack, makes it clearer.

**Comment by amenat** [comment]
Emojis are certainly important :) 

I'll get it fixed soon. Thanks for detailed report.
